package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Actor;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    int insert(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    Actor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    List<Actor> selectAll();

    List<Actor> selectByFirstNameAndLastName(@Param("firstName") String firstName, @Param("lastName") String lastName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ACTOR
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    int updateByPrimaryKey(Actor record);
}