package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Producer;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ProducerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    int insert(Producer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    Producer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    List<Producer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    int updateByPrimaryKey(Producer record);
}