package lt.vu.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.ID
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.YEAR
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.PRODUCER_ID
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    private Integer producerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.ID
     *
     * @return the value of PUBLIC.MOVIE.ID
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.ID
     *
     * @param id the value for PUBLIC.MOVIE.ID
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.NAME
     *
     * @return the value of PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.NAME
     *
     * @param name the value for PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.YEAR
     *
     * @return the value of PUBLIC.MOVIE.YEAR
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.YEAR
     *
     * @param year the value for PUBLIC.MOVIE.YEAR
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.PRODUCER_ID
     *
     * @return the value of PUBLIC.MOVIE.PRODUCER_ID
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public Integer getProducerId() {
        return producerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.PRODUCER_ID
     *
     * @param producerId the value for PUBLIC.MOVIE.PRODUCER_ID
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public void setProducerId(Integer producerId) {
        this.producerId = producerId;
    }

    public Producer getProducer(){ return producer; }
    public void setProducer(Producer producer){ this.producer = producer; }
    private Producer producer;

    public List<Actor> getActorList(){ return actorList; }
    public void setActorList(List<Actor> actorList){ this.actorList = actorList; }
    private List<Actor> actorList = new ArrayList<Actor>();
}