package lt.vu.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class Producer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCER.ID
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCER.FIRSTNAME
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCER.LASTNAME
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    private String lastname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCER.ID
     *
     * @return the value of PUBLIC.PRODUCER.ID
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCER.ID
     *
     * @param id the value for PUBLIC.PRODUCER.ID
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCER.FIRSTNAME
     *
     * @return the value of PUBLIC.PRODUCER.FIRSTNAME
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCER.FIRSTNAME
     *
     * @param firstname the value for PUBLIC.PRODUCER.FIRSTNAME
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCER.LASTNAME
     *
     * @return the value of PUBLIC.PRODUCER.LASTNAME
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCER.LASTNAME
     *
     * @param lastname the value for PUBLIC.PRODUCER.LASTNAME
     *
     * @mbg.generated Sun Apr 26 01:46:49 EEST 2020
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public List<Movie> getMovieList(){ return movieList; }
    public void setMovieList(List<Movie> movieList){ this.movieList = movieList; }

    private List<Movie> movieList = new ArrayList<Movie>();
}